version: '3'

services:
    backend:
        build:
            context: ./api
        command: python app.py runserver --bind 0.0.0.0:8000
        ports:
          - "8000:8000"
    frontend:
        build:
            context: ./sys-stats
        volumes:
            - react_build:/sys-stats/build
    nginx:
        image: nginx:latest
        ports:
            - 80:8080
        volumes:
            - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
            - react_build:/var/www/react
        depends_on:
            - backend
            - frontend
volumes:
    react_build:

